# Generated by Django 4.2.16 on 2024-10-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='geade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
